### ISSUE TITLE
Contributors headcount is not increasing in readme 💭

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Annoying-submit-button#8] opened 2022-10-06 12:26 UTC
### Contributors Count is not increasing in readme file 💭. It is showing only 4 names

**Comment by vaibhavmishra4g** [comment] 2022-10-06 14:42
Assign me the task I'll resolve it

**Comment by vaibhavmishra4g** [comment] 2022-10-06 14:47
yep it has some refresh bug or it'll take 24 hrs I checked it on the website

**Comment by vikkastiwari** [comment] 2022-10-08 09:51
@fineanmol, The issue is fixed now the contributor's count is updated correctly.

**Closed** 2022-10-08 10:05 UTC
Labels: help wanted, hacktoberfest-accepted
